{
    'name': 'JJM Report Payment',
    'version': '1.0',
    'category': 'Extra Tools',
    'summary': 'Reporte de Cobranzas',
    'license': 'AGPL-3',
    'author': 'Romina Bazan',
    'maintainer': 'Romina Bazan',
    'depends': ['base', 
                'sale',
                'account',
                'contract',
                ],
    'demo': [],
    'data': [
        # 'security/ir.model.access.csv',
        'report/template.xml',
        'wizard/view.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
